# NUMPY BASIC
- NumPy used to working array; Num->Numerical; Py->Python
- It also has functions for working in domain of linear algebra, fourier transform, and matrices
- To speed up the process using array in numpy rather than list


In [1]:
# Import Numpy library -> terminal or Anaconda prompt type -> pip install numpy
# alias -> numpy as np
import numpy as np
print(np.__version__)

1.20.1


## Creating an Array
    1-D Arrays
- To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray

In [2]:
# The array object in NumPy is called ndarray
lst = {2,3,7,9,3,6,12,45,99,23,92,100,3.14,56.98}
arr = np.array(lst) 
print(arr)

{2, 3, 99, 100, 6, 7, 3.14, 9, 12, 45, 23, 56.98, 92}


## 2-D Arrays
- 2-D Arrays are often used to represent matrix
- Note: NumPy has a whole sub module dedicated towards matrix operations called numpy.mat

In [34]:
a = [1,2,3,4,5]
b = [26,45,67,89,12]
c = [0,56,34,95,112]

arr = np.array([a,b,c])

In [35]:
arr

array([[  1,   2,   3,   4,   5],
       [ 26,  45,  67,  89,  12],
       [  0,  56,  34,  95, 112]])

## 3-D arrays

In [5]:
a = ([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr = np.array(a)
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

## Number of Dimensions
- The number of dimensions by using the ndmin argument

In [6]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Multi-Dimensional Arrays

In [7]:
a = [10,20,30,30,40,50]
arr = np.array(a, ndmin = 6)
arr

array([[[[[[10, 20, 30, 30, 40, 50]]]]]])

In [8]:
print("Number of Dimentions: ", arr.ndim,  "\nArray:", arr)

Number of Dimentions:  6 
Array: [[[[[[10 20 30 30 40 50]]]]]]


## Array Indexing
- Access an array element by referring to its index number

In [9]:
# 1-D Arrays
a = [1,2,3,4]
arr = np.array(a)
print('3rd element:',arr[2])

3rd element: 3


In [10]:
# 2-D Arrays
a = ([1,2,3,4],[21,31,41,51])
arr = np.array(a)
print('3rd element on the 2nd array:',arr[1,2])

3rd element on the 2nd array: 41


In [11]:
arr[:,:] #select all row column

array([[ 1,  2,  3,  4],
       [21, 31, 41, 51]])

In [12]:
arr[0:2,:] # until row 2 pickup and show; OUTPUT: first 2 rows which index 0,1

array([[ 1,  2,  3,  4],
       [21, 31, 41, 51]])

In [13]:
arr[0:2,0:2] #first 2 columns picking up

array([[ 1,  2],
       [21, 31]])

In [14]:
arr[0:2,1:3] # 0:2->Rows 0,1; 1:3->Columns 1,2

array([[ 2,  3],
       [31, 41]])

In [15]:
arr[1:2,1:4] 

array([[31, 41, 51]])

## arange()
- SYNTAX: arange([start,] stop[, step], dtype = None])

In [16]:
arr = np.arange(0,11)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr =np.arange(0,11,2)

In [31]:
arr

array([ 0,  2,  4,  6,  8, 10])

## linspace() 
- creating numeric sequences

In [38]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [20]:
# add
a1 = ([1,2,3,4])
arr = np.array(a1)
print(arr[0] + arr[1])

3


In [21]:
# 3-D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


## negative indexing to access an array from the end

In [22]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1]) #negative indexing to access an array from the end

Last element from 2nd dim:  10


## Shape
- NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [23]:
lst = ([2,3,7,9,3,6,12,45,99,23,92,100,3.14,56.98])
arr = np.array(lst) 

In [24]:
print(arr.shape)

(14,)


In [25]:
# 2-D Arrays
a = [1,2,3,4,5]
b = [26,45,67,89,12]
c = [0,56,34,95,112]

arr = np.array([a,b,c]) 

In [26]:
arr

array([[  1,   2,   3,   4,   5],
       [ 26,  45,  67,  89,  12],
       [  0,  56,  34,  95, 112]])

In [27]:
arr.shape

(3, 5)

In [28]:
arr.reshape(5,3) #rows 5  columns 3

array([[  1,   2,   3],
       [  4,   5,  26],
       [ 45,  67,  89],
       [ 12,   0,  56],
       [ 34,  95, 112]])

In [29]:
arr.reshape(1,15)

array([[  1,   2,   3,   4,   5,  26,  45,  67,  89,  12,   0,  56,  34,
         95, 112]])

In [71]:
# create an array and reshape
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [74]:
arr1 = np.arange(0,10).reshape(2,5)
arr2 = np.arange(10,20).reshape(2,5)

In [76]:
arr1 + arr2

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

## Copy Function and Broadcasting

In [44]:
lst = ([2,3,7,9,3,6,12,45,99,23,92,100,3.14,56.98])
arr = np.array(lst) 
arr

array([  2.  ,   3.  ,   7.  ,   9.  ,   3.  ,   6.  ,  12.  ,  45.  ,
        99.  ,  23.  ,  92.  , 100.  ,   3.14,  56.98])

In [45]:
arr[3:4] = 0

In [48]:
print(arr)

[  2.     3.     7.     0.     3.     6.    12.    45.    99.    23.
  92.   100.     3.14  56.98]


In [49]:
arr1 = arr

In [50]:
# reference type
arr1[3:4] = 10
print(arr1)

[  2.     3.     7.    10.     3.     6.    12.    45.    99.    23.
  92.   100.     3.14  56.98]


In [53]:
# reference type 
arr

array([  2.  ,   3.  ,   7.  ,  10.  ,   3.  ,   6.  ,  12.  ,  45.  ,
        99.  ,  23.  ,  92.  , 100.  ,   3.14,  56.98])

- In order to prevent reference type we will use copy

In [55]:
arr1 = arr.copy()

In [54]:
print(arr)
arr1[3:4] = 9
print(arr1)

[  2.     3.     7.    10.     3.     6.    12.    45.    99.    23.
  92.   100.     3.14  56.98]
[  2.     3.     7.     9.     3.     6.    12.    45.    99.    23.
  92.   100.     3.14  56.98]


In [60]:
# Exploratory Data Analysis [conditions]

var = 1

arr < 23 #condition

array([ True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False,  True, False])

In [61]:
arr * 2 #operation

array([  4.  ,   6.  ,  14.  ,  18.  ,   6.  ,  12.  ,  24.  ,  90.  ,
       198.  ,  46.  , 184.  , 200.  ,   6.28, 113.96])

In [67]:
arr[arr < 4] #condition with showing elements

array([2.  , 3.  , 3.  , 3.14])

## np.ones()

In [77]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [81]:
np.ones((4,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## Random Distribution
- Random values in a given shape

In [83]:
np.random.rand(5,3) # values are 0 - 1

array([[0.05002708, 0.19818657, 0.28245499],
       [0.57735014, 0.40281791, 0.32103584],
       [0.76312767, 0.0559974 , 0.77296833],
       [0.16567866, 0.50444038, 0.70688243],
       [0.48938676, 0.68639722, 0.18225944]])

In [84]:
arr5 = np.random.randn(5,3) # values from the "standard normal" distribution

array([[ 1.54357345, -2.65915581,  0.65079573],
       [-0.66143663, -0.95709739, -0.25932439],
       [-2.03341024, -0.48070421, -0.17739725],
       [-0.56459993,  0.67195649, -0.55513387],
       [-0.26459779, -1.00403758,  1.092991  ]])

In [94]:
np.random.randint(0,100,8)

array([40, 47, 41, 67, 79, 13, 45,  9])

In [95]:
np.random.randint(0,100,8).reshape(4,2)

array([[ 7, 43],
       [33, 17],
       [58,  7],
       [34, 48]])

In [105]:
np.random.random_sample(5)

array([0.98524007, 0.91927993, 0.72379201, 0.50510905, 0.81971974])

In [107]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [108]:
arr.reshape(2, 4).base

array([1, 2, 3, 4, 5, 6, 7, 8])

# Data Science is a branch of computer science where we study how to store, use and analyze data for deriving information from it.